POST http://localhost:3000/home

Content-Type: application/json

{
    "titulo": "Tarefa 01",
    "descricao": "Tarefa para criar tarefa",
    "data": {{{$datetime rfc1123}}}


},

{
    "titulo": "Tarefa 02",
    "descricao": "Tarefa para criar tarefa",
    "data": {{{$datetime rfc1123}}}


}

###


GET http://localhost:3000/home

